[package]
name = "safetensors-python"
version = "0.5.3"
edition = "2021"
rust-version = "1.74"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "safetensors_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.5", features = ["abi3", "abi3-py38"] }
memmap2 = "0.9.5"
serde_json = "1.0.140"

# memmap2 = { version = "0.9.5", default-features = false, features = ["std"], optional = true }
libc = { version = "0.2.172", default-features = false, features = ["std"], optional = true }
# pyo3 = { version = "0.23.5", default-features = false, features = ["std"], optional = true }
cfg-if = { version = "1.0.0", default-features = false, optional = true }
indoc = { version = "2.0.6", default-features = false, optional = true }
memoffset = { version = "0.9.1", default-features = false, optional = true }
# [build-dependencies] = { version = "", default-features = false, features = ["std"], optional = true }
autocfg = { version = "1.4.0", default-features = false, optional = true }
once_cell = { version = "1.21.3", default-features = false, features = ["std"], optional = true }
pyo3-ffi = { version = "0.23.5", default-features = false, optional = true }
# [build-dependencies] = { version = "", default-features = false, features = ["std"], optional = true }
pyo3-build-config = { version = "0.23.5", default-features = false, optional = true }
target-lexicon = { version = "0.12.16", default-features = false, features = ["std"], optional = true }
# [build-dependencies] = { version = "", default-features = false, features = ["std"], optional = true }
pyo3-macros = { version = "0.23.5", default-features = false, optional = true }
proc-macro2 = { version = "1.0.95", default-features = false, optional = true }
unicode-ident = { version = "1.0.18", default-features = false, optional = true }
pyo3-macros-backend = { version = "0.23.5", default-features = false, optional = true }
heck = { version = "0.5.0", default-features = false, optional = true }
quote = { version = "1.0.40", default-features = false, optional = true }
syn = { version = "2.0.101", default-features = false, optional = true }
# [build-dependencies] = { version = "", default-features = false, features = ["std"], optional = true }
unindent = { version = "0.2.4", default-features = false, optional = true }
# [build-dependencies] = { version = "", default-features = false, features = ["std"], optional = true }
serde = { version = "1.0.219", default-features = false, features = ["std"], optional = true }
serde_derive = { version = "1.0.219", default-features = false, optional = true }
# serde_json = { version = "1.0.140", default-features = false, features = ["std"], optional = true }
itoa = { version = "1.0.15", default-features = false, optional = true }
memchr = { version = "2.7.4", default-features = false, features = ["std"], optional = true }
ryu = { version = "1.0.20", default-features = false, optional = true }

[dependencies.safetensors]
path = "../../safetensors"
