[package]
name = "safetensors-python"
version = "0.4.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "safetensors_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22" }
memmap2 = "0.9"
serde_json = "1.0"
libc = { version = "0.2.155", default-features = false, features = ["std"], optional = true }
cfg-if = { version = "1.0.0", default-features = false, optional = true }
indoc = { version = "2.0.5", default-features = false, optional = true }
memoffset = { version = "0.9.1", default-features = false, optional = true }
# [build-dependencies]
autocfg = { version = "1.3.0", default-features = false, optional = true }
once_cell = { version = "1.19.0", default-features = false, features = ["std"], optional = true }
pyo3-ffi = { version = "0.22.2", default-features = false, optional = true }
# [build-dependencies]
pyo3-build-config = { version = "0.22.2", default-features = false, optional = true }
target-lexicon = { version = "0.12.16", default-features = false, features = ["std"], optional = true }
# [build-dependencies]
pyo3-macros = { version = "0.22.2", default-features = false, optional = true }
proc-macro2 = { version = "1.0.95", default-features = false, optional = true }
unicode-ident = { version = "1.0.12", default-features = false, optional = true }
pyo3-macros-backend = { version = "0.22.2", default-features = false, optional = true }
heck = { version = "0.5.0", default-features = false, optional = true }
quote = { version = "1.0.36", default-features = false, optional = true }
syn = { version = "2.0.101", default-features = false, optional = true }
# [build-dependencies]
unindent = { version = "0.2.3", default-features = false, optional = true }
serde = { version = "1.0.219", default-features = false, features = ["std"], optional = true }
serde_derive = { version = "1.0.219", default-features = false, optional = true }
itoa = { version = "1.0.11", default-features = false, optional = true }
memchr = { version = "2.7.4", default-features = false, features = ["std"], optional = true }
ryu = { version = "1.0.18", default-features = false, optional = true }
portable-atomic = { version = "1.7.0", default-features = false, features = ["std"], optional = true }

[dependencies.safetensors]
path = "../../safetensors"
